# Generated by Django 4.2.3 on 2023-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="moviemodel",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
